'use client'

import Link from 'next/link'
import { ArrowLeft, CheckCircle2, HeartPulse, Loader2, MapPin, RefreshCw, ShieldAlert, Shirt, Sparkles, Umbrella, Wind } from 'lucide-react'
import { useLocations } from '@/lib/weather/use-locations'
import { useWeather } from '@/lib/weather/use-weather'
import { createRecommendations, type Recommendation } from '@/lib/recommendations'

const icons = { outdoor: CheckCircle2, travel: Umbrella, clothing: Shirt, health: HeartPulse, precaution: ShieldAlert }
const tones = { good: 'border-emerald-500/20 bg-emerald-500/8', info: 'border-primary/20 bg-primary/8', warning: 'border-amber-500/20 bg-amber-500/8', urgent: 'border-destructive/25 bg-destructive/10' }

export default function AIRecommendationsPage() {
  const { active } = useLocations()
  const { data, loading, error, refresh } = useWeather(active?.latitude, active?.longitude)
  const recommendations = data ? createRecommendations({ weather: { temperatureC: data.current.tempC, apparentTemperatureC: data.current.apparentC, precipitationProbability: data.daily[0]?.precipProb, windSpeedKmh: data.current.windKmh, uvIndex: data.uvIndexMax, weatherCode: data.current.code }, airQuality: data.airQuality }) : []
  const location = active ? `${active.name}${active.region ? `, ${active.region}` : ''}` : 'Selected location'
  return <main className="min-h-screen bg-background text-foreground"><header className="sticky top-0 z-20 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-4 md:px-8"><div className="flex items-center gap-3"><Link href="/dashboard" aria-label="Back to dashboard" className="rounded-lg p-2 hover:bg-muted"><ArrowLeft size={18}/></Link><div><p className="text-xs uppercase tracking-[.2em] text-muted-foreground">Mausam intelligence</p><p className="font-semibold">AI recommendations</p></div></div><button onClick={refresh} aria-label="Refresh recommendations" className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><RefreshCw size={18}/></button></div></header><div className="mx-auto max-w-5xl px-4 py-8 md:px-8"><div className="mb-8"><p className="flex items-center gap-2 text-sm text-muted-foreground"><MapPin size={14} className="text-primary"/> {location}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight md:text-4xl">Make today easier</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Practical guidance generated from the live forecast, air quality, and conditions at your selected location.</p></div>{error && <div role="alert" className="mb-5 rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}{loading && !data ? <div className="flex min-h-80 items-center justify-center text-muted-foreground"><Loader2 className="mr-2 animate-spin" size={18}/> Building recommendations…</div> : <><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-5"><Sparkles className="text-primary" size={20}/><p className="mt-4 text-2xl font-semibold">{recommendations.length}</p><p className="text-sm text-muted-foreground">Personalized pointers</p></div><div className="rounded-2xl border border-border bg-card p-5"><Wind className="text-primary" size={20}/><p className="mt-4 text-2xl font-semibold">{data?.current.windKmh ?? '—'} km/h</p><p className="text-sm text-muted-foreground">Current wind signal</p></div><div className="rounded-2xl border border-border bg-card p-5"><Umbrella className="text-primary" size={20}/><p className="mt-4 text-2xl font-semibold">{data?.daily[0]?.precipProb ?? '—'}%</p><p className="text-sm text-muted-foreground">Rain chance today</p></div></div><div className="mt-5 grid gap-4">{recommendations.map((item) => <RecommendationCard key={`${item.category}-${item.title}`} item={item}/>)}</div><div className="mt-6 rounded-2xl border border-border bg-card p-5 text-sm text-muted-foreground"><p className="font-medium text-foreground">How to use these suggestions</p><p className="mt-2 leading-6">These are guidance signals, not medical or emergency advice. Conditions can change quickly, so refresh before a long trip or outdoor activity.</p></div></>}</div></main>
}

function RecommendationCard({ item }: { item: Recommendation }) { const Icon = icons[item.category]; return <article className={`rounded-2xl border p-5 ${tones[item.severity]}`}><div className="flex items-start gap-4"><div className="rounded-xl bg-background/70 p-3 text-primary"><Icon size={20}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold">{item.title}</p>{item.value && <span className="rounded-full bg-background/70 px-2.5 py-1 text-xs font-medium text-muted-foreground">{item.value}</span>}</div><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{item.guidance}</p></div></div></article> }
