'use client'

import { useMemo, useState } from 'react'
import { Bell, Bookmark, Check, ChevronDown, CircleAlert, CloudRain, Droplets, Heart, Inbox, Mail, MapPin, MoreHorizontal, Search, Settings2, ShieldAlert, SlidersHorizontal, Smartphone, Sparkles, Thermometer, Trash2, Wind, X } from 'lucide-react'
import type { AlertType, NotificationSettings, WeatherAlert } from '@/lib/alerts/service'

type Props = { initialAlerts: WeatherAlert[]; initialSettings: NotificationSettings }
const filters: Array<'All' | AlertType> = ['All', 'Severe Weather', 'Daily Forecast', 'Air Quality', 'Temperature', 'Precipitation']
const iconByType = { 'Severe Weather': ShieldAlert, 'Daily Forecast': CloudRain, 'Air Quality': Wind, Temperature: Thermometer, Precipitation: Droplets }
const toneBySeverity = { critical: 'bg-red-50 text-red-700 ring-red-100', high: 'bg-orange-50 text-orange-700 ring-orange-100', medium: 'bg-amber-50 text-amber-700 ring-amber-100', low: 'bg-slate-50 text-slate-600 ring-slate-200' }

export function AlertsDashboard({ initialAlerts, initialSettings }: Props) {
  const [alerts, setAlerts] = useState(initialAlerts)
  const [settings, setSettings] = useState(initialSettings)
  const [filter, setFilter] = useState<(typeof filters)[number]>('All')
  const [query, setQuery] = useState('')
  const [sort, setSort] = useState('Newest first')
  const [selected, setSelected] = useState<WeatherAlert | null>(null)
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [showArchived, setShowArchived] = useState(false)

  const visible = useMemo(() => alerts.filter((alert) => (showArchived ? alert.archived : !alert.archived) && (filter === 'All' || alert.type === filter) && `${alert.title} ${alert.location} ${alert.detail}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'Oldest first' ? a.id.localeCompare(b.id) : b.id.localeCompare(a.id)), [alerts, filter, query, showArchived, sort])
  const unreadCount = alerts.filter((a) => a.unread && !a.archived).length
  const updateAlert = (id: string, patch: Partial<WeatherAlert>) => setAlerts((current) => current.map((alert) => alert.id === id ? { ...alert, ...patch } : alert))

  return <main className="min-h-screen bg-[#f7f9fb] text-slate-950">
    <header className="border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-6 py-4 lg:px-10"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-slate-400">Mausam AI</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Alerts & Notifications</h1></div><div className="flex items-center gap-3"><button onClick={() => setSettingsOpen(!settingsOpen)} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-600 transition hover:border-slate-300 hover:bg-slate-50"><Settings2 size={16} /> Notification settings</button><div className="grid size-9 place-items-center rounded-full bg-slate-900 text-sm font-semibold text-white">MA</div></div></div></header>
    <div className="mx-auto max-w-[1440px] px-6 py-8 lg:px-10"><div className="mb-7 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm text-slate-500">Stay ahead of the weather that matters to you.</p><div className="mt-4 flex items-center gap-2 text-sm text-slate-500"><span className="inline-flex items-center gap-1.5 rounded-full bg-white px-3 py-1.5 shadow-sm ring-1 ring-slate-200"><Bell size={15} className="text-orange-500" /> {unreadCount} unread alerts</span><span className="text-slate-300">•</span><span>Updated just now</span></div></div><div className="relative w-full md:w-72"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input aria-label="Search alerts" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search alerts" className="w-full rounded-lg border border-slate-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none ring-orange-400 transition focus:ring-2" /></div></div>
      <div className="mb-6 flex gap-2 overflow-x-auto pb-1">{filters.map((item) => <button key={item} onClick={() => setFilter(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-medium transition ${filter === item ? 'bg-slate-900 text-white shadow-sm' : 'bg-white text-slate-500 ring-1 ring-slate-200 hover:text-slate-900'}`}>{item}</button>)}</div>
      <div className="mb-4 flex items-center justify-between"><p className="text-sm font-medium text-slate-500">{visible.length} {showArchived ? 'archived' : 'active'} alerts</p><div className="flex items-center gap-2"><button onClick={() => setShowArchived(!showArchived)} className="inline-flex items-center gap-1.5 rounded-md px-2 py-1.5 text-sm text-slate-500 hover:bg-white"><Inbox size={15} /> {showArchived ? 'Active alerts' : 'Archived'}</button><label className="inline-flex items-center gap-1.5 text-sm text-slate-500"><SlidersHorizontal size={15} /><select value={sort} onChange={(e) => setSort(e.target.value)} className="bg-transparent outline-none"><option>Newest first</option><option>Oldest first</option></select></label></div></div>
      <div className="grid gap-4">{visible.map((alert) => <AlertCard key={alert.id} alert={alert} onOpen={() => { updateAlert(alert.id, { unread: false }); setSelected(alert) }} onFavorite={() => updateAlert(alert.id, { favorite: !alert.favorite })} onArchive={() => updateAlert(alert.id, { archived: !alert.archived })} onDelete={() => setAlerts((all) => all.filter((item) => item.id !== alert.id))} />)}{visible.length === 0 && <div className="rounded-xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><CircleAlert className="mx-auto text-slate-300" /><h2 className="mt-3 font-semibold">No alerts found</h2><p className="mt-1 text-sm text-slate-500">Try another search or filter.</p></div>}</div>
      <section className="mt-8 rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-orange-600"><Sparkles size={17} /><p className="text-sm font-semibold">AI weather insights</p></div><h2 className="mt-2 text-lg font-semibold">Your alerts, summarized</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">The most important thing to know: extreme heat in Phoenix and storms in Austin are the only high-impact conditions in your alert feed today.</p></div><button className="hidden rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-600 hover:bg-slate-50 sm:block">View insights</button></div></section>
      {settingsOpen && <SettingsPanel settings={settings} onChange={setSettings} onClose={() => setSettingsOpen(false)} />}
      {selected && <DetailPanel alert={selected} onClose={() => setSelected(null)} />}
    </div></main>
}

function AlertCard({ alert, onOpen, onFavorite, onArchive, onDelete }: { alert: WeatherAlert; onOpen: () => void; onFavorite: () => void; onArchive: () => void; onDelete: () => void }) { const Icon = iconByType[alert.type]; return <article className={`group relative rounded-xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${alert.unread ? 'border-orange-200' : 'border-slate-200'}`}><div className="flex gap-4"><div className={`grid size-11 shrink-0 place-items-center rounded-xl ring-1 ${toneBySeverity[alert.severity]}`}><Icon size={21} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-semibold uppercase tracking-wider text-slate-400">{alert.type}</span>{alert.unread && <span className="size-2 rounded-full bg-orange-500" aria-label="Unread" />}</div><button onClick={onOpen} className="mt-1 text-left text-base font-semibold text-slate-900 hover:text-orange-600">{alert.title}</button></div><button onClick={onFavorite} aria-label={alert.favorite ? 'Remove favorite' : 'Add favorite'} className="rounded-md p-1.5 text-slate-300 hover:bg-slate-50 hover:text-orange-500">{alert.favorite ? <Heart size={18} fill="currentColor" className="text-orange-500" /> : <Heart size={18} />}</button></div><p className="mt-2 flex items-center gap-1.5 text-sm font-medium text-slate-600"><MapPin size={14} /> {alert.location}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{alert.detail}</p><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 text-xs text-slate-400"><span>{alert.relativeTime}</span>{alert.expiresAt && <span className="inline-flex items-center gap-1"><Bell size={13} /> Expires {alert.expiresAt}</span>}{alert.temperature && <span className="inline-flex items-center gap-1"><Thermometer size={13} /> {alert.temperature}</span>}<div className="ml-auto flex items-center gap-1"><button onClick={onOpen} className="rounded-md px-2 py-1.5 font-medium text-slate-500 hover:bg-slate-50 hover:text-slate-900">View details</button><button onClick={onArchive} className="rounded-md p-1.5 hover:bg-slate-50" aria-label="Archive alert"><Bookmark size={15} /></button><button onClick={onDelete} className="rounded-md p-1.5 hover:bg-red-50 hover:text-red-600" aria-label="Delete alert"><Trash2 size={15} /></button></div></div></div></div></article> }

function DetailPanel({ alert, onClose }: { alert: WeatherAlert; onClose: () => void }) { return <div className="fixed inset-0 z-20 flex items-end justify-center bg-slate-950/20 p-0 backdrop-blur-[2px] sm:items-center sm:p-6" onClick={onClose}><aside onClick={(e) => e.stopPropagation()} className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-t-2xl bg-white p-6 shadow-2xl sm:rounded-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-orange-600">{alert.type}</p><h2 className="mt-2 text-xl font-semibold">{alert.title}</h2><p className="mt-1 text-sm text-slate-500">{alert.location} · {alert.timestamp}</p></div><button onClick={onClose} aria-label="Close details" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={18} /></button></div><div className="mt-6 rounded-xl bg-orange-50 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-orange-700"><Sparkles size={16} /> Mausam AI insight</div><p className="mt-2 text-sm leading-6 text-orange-950">{alert.insight ?? 'Keep an eye on changing conditions and check back for the latest forecast.'}</p></div><p className="mt-6 text-sm leading-7 text-slate-600">{alert.detail}</p><button onClick={onClose} className="mt-6 w-full rounded-lg bg-slate-900 px-4 py-3 text-sm font-semibold text-white hover:bg-slate-800">Done</button></aside></div> }

function SettingsPanel({ settings, onChange, onClose }: { settings: NotificationSettings; onChange: (next: NotificationSettings) => void; onClose: () => void }) { const rows = [['severeWeather', 'Severe weather', 'Critical warnings and watches'], ['dailyForecast', 'Daily forecast', 'A morning summary for your saved places'], ['airQuality', 'Air quality', 'Smoke, pollen, and AQI changes'], ['temperature', 'Temperature changes', 'Unusual highs, lows, and frost'], ['precipitation', 'Precipitation', 'Heavy rain, snow, and hail']] as const; return <div className="fixed inset-0 z-20 flex justify-end bg-slate-950/20 backdrop-blur-[2px]" onClick={onClose}><aside onClick={(e) => e.stopPropagation()} className="h-full w-full max-w-md overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-orange-600">Preferences</p><h2 className="mt-1 text-xl font-semibold">Notification settings</h2></div><button onClick={onClose} aria-label="Close settings" className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={18} /></button></div><div className="mt-8"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-400">Alert types</p>{rows.map(([key, title, description]) => <label key={key} className="flex cursor-pointer items-center justify-between border-b border-slate-100 py-4"><span><span className="block text-sm font-medium text-slate-800">{title}</span><span className="mt-1 block text-xs text-slate-400">{description}</span></span><input type="checkbox" checked={settings[key]} onChange={(e) => onChange({ ...settings, [key]: e.target.checked })} className="size-4 accent-orange-500" /></label>)}</div><div className="mt-8"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-400">Delivery channels</p>{(['email', 'push', 'sms'] as const).map((key) => <label key={key} className="flex items-center justify-between border-b border-slate-100 py-4"><span className="flex items-center gap-3 text-sm font-medium capitalize text-slate-800">{key === 'email' ? <Mail size={17} /> : key === 'push' ? <Smartphone size={17} /> : <MessageIcon />} {key}</span><input type="checkbox" checked={settings[key]} onChange={(e) => onChange({ ...settings, [key]: e.target.checked })} className="size-4 accent-orange-500" /></label>)}</div><div className="mt-8 rounded-lg bg-slate-50 p-4 text-sm leading-6 text-slate-500"><Check size={16} className="mb-1 text-emerald-600" /> Changes save automatically for this preview.</div></aside></div> }
function MessageIcon() { return <span className="grid size-[17px] place-items-center rounded border border-current text-[9px]">SMS</span> }
